// <auto-generated />
using System;
using CloudConfigurationHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudConfigurationHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConfigurationHubDbContext))]
    [Migration("20260831061102_CreateConfigurationHubSchema")]
    partial class CreateConfigurationHubSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("CloudConfigurationHub.Domain.Projects.ConfigDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Group", "Key")
                        .IsUnique();

                    b.ToTable("ConfigDefinitions", (string)null);
                });

            modelBuilder.Entity("CloudConfigurationHub.Domain.Projects.ConfigDraftValue", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "EnvironmentId", "ConfigurationId");

                    b.ToTable("ConfigDraftValues", (string)null);
                });

            modelBuilder.Entity("CloudConfigurationHub.Domain.Projects.ConfigRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "EnvironmentId", "Version")
                        .IsUnique();

                    b.ToTable("ConfigReleases", (string)null);
                });

            modelBuilder.Entity("CloudConfigurationHub.Domain.Projects.ConfigReleaseValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("ConfigReleaseValues", (string)null);
                });

            modelBuilder.Entity("CloudConfigurationHub.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessKeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("CloudConfigurationHub.Domain.Projects.ProjectEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("ProjectEnvironments", (string)null);
                });

            modelBuilder.Entity("CloudConfigurationHub.Domain.Projects.ConfigDefinition", b =>
                {
                    b.HasOne("CloudConfigurationHub.Domain.Projects.Project", null)
                        .WithMany("Configurations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudConfigurationHub.Domain.Projects.ConfigDraftValue", b =>
                {
                    b.HasOne("CloudConfigurationHub.Domain.Projects.Project", null)
                        .WithMany("_draftValues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudConfigurationHub.Domain.Projects.ConfigRelease", b =>
                {
                    b.HasOne("CloudConfigurationHub.Domain.Projects.Project", null)
                        .WithMany("Releases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudConfigurationHub.Domain.Projects.ConfigReleaseValue", b =>
                {
                    b.HasOne("CloudConfigurationHub.Domain.Projects.ConfigRelease", null)
                        .WithMany("Values")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudConfigurationHub.Domain.Projects.ProjectEnvironment", b =>
                {
                    b.HasOne("CloudConfigurationHub.Domain.Projects.Project", null)
                        .WithMany("Environments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudConfigurationHub.Domain.Projects.ConfigRelease", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("CloudConfigurationHub.Domain.Projects.Project", b =>
                {
                    b.Navigation("Configurations");

                    b.Navigation("Environments");

                    b.Navigation("Releases");

                    b.Navigation("_draftValues");
                });
#pragma warning restore 612, 618
        }
    }
}
