namespace CloudConfigurationHub.App.Components;

internal static class ManagementWorkbenchText {
    internal static string Translate(string language, string zh, string en) {
        if (language == "en") {
            return en;
        }

        return language switch {
            "ja" => Japanese.TryGetValue(zh, out var value) ? value : zh,
            "ko" => Korean.TryGetValue(zh, out var value) ? value : zh,
            "es" => Spanish.TryGetValue(zh, out var value) ? value : zh,
            _ => zh
        };
    }

    internal static readonly IReadOnlyDictionary<string, string> Japanese = new Dictionary<string, string> {
        ["配置管理"] = "設定管理",
        ["选择项目"] = "プロジェクトを選択",
        ["搜索项目"] = "プロジェクトを検索",
        ["暂无数据"] = "データなし",
        ["请先在“项目管理”中创建一个项目"] = "先に「プロジェクト管理」でプロジェクトを作成してください",
        ["按环境"] = "環境別",
        ["按配置"] = "設定別",
        ["选择一个环境，管理该环境下的全部配置"] = "環境を選択して、その環境の設定を管理します",
        ["选择一个配置项，管理它在所有环境下的值"] = "設定項目を選択して、全環境の値を管理します",
        ["该项目暂无环境，请先在项目设置中添加环境"] = "このプロジェクトには環境がありません",
        ["搜索配置键"] = "設定キーを検索",
        ["新建配置项"] = "設定を作成",
        ["还没有配置项"] = "設定はまだありません",
        ["新建后会显示在这里"] = "作成した設定はここに表示されます",
        ["创建后可在这里维护各环境的配置值"] = "作成後、各環境の値をここで管理できます",
        ["值"] = "値",
        ["更新于"] = "更新日時",
        ["操作"] = "操作",
        ["选择配置项"] = "設定項目を選択",
        ["各环境取值"] = "各環境の値",
        ["项目管理"] = "プロジェクト管理",
        ["个项目 · 管理所有项目及其环境"] = "件のプロジェクト · すべてのプロジェクトと環境を管理",
        ["新建项目"] = "プロジェクトを作成",
        ["搜索项目名称或标识"] = "プロジェクト名またはキーを検索",
        ["个环境"] = "環境",
        ["项配置"] = "設定",
        ["创建于"] = "作成日",
        ["管理配置"] = "設定管理",
        ["编辑项目"] = "プロジェクトを編集",
        ["编辑配置项"] = "設定を編集",
        ["名称"] = "名前",
        ["标识"] = "キー",
        ["项目唯一标识，用于 API 调用"] = "API 呼び出しで使う一意のプロジェクトキー",
        ["描述"] = "説明",
        ["选填"] = "任意",
        ["环境"] = "環境",
        ["多个环境用逗号分隔"] = "環境はカンマで区切ってください",
        ["取消"] = "キャンセル",
        ["保存"] = "保存",
        ["配置键，项目内唯一"] = "プロジェクト内で一意の設定キー",
        ["敏感配置"] = "機密設定",
        ["环境取值"] = "環境の値",
        ["删除"] = "削除",
        ["关闭"] = "閉じる",
        ["删除确认"] = "削除確認",
        ["请输入名称"] = "名前を入力してください",
        ["请输入配置键"] = "設定キーを入力してください",
        ["确定删除该项目吗？其下所有配置将一并删除，此操作不可恢复。"] = "このプロジェクトを削除しますか？配下の設定も削除され、元に戻せません。",
        ["确定删除该配置项吗？它在所有环境下的值都将被删除。"] = "この設定を削除しますか？すべての環境の値も削除されます。"
    };

    internal static readonly IReadOnlyDictionary<string, string> Korean = new Dictionary<string, string> {
        ["配置管理"] = "구성 관리",
        ["选择项目"] = "프로젝트 선택",
        ["搜索项目"] = "프로젝트 검색",
        ["暂无数据"] = "데이터 없음",
        ["请先在“项目管理”中创建一个项目"] = "먼저 프로젝트 관리에서 프로젝트를 생성하세요",
        ["按环境"] = "환경별",
        ["按配置"] = "구성별",
        ["选择一个环境，管理该环境下的全部配置"] = "환경을 선택해 해당 환경의 구성을 관리합니다",
        ["选择一个配置项，管理它在所有环境下的值"] = "구성 항목을 선택해 모든 환경의 값을 관리합니다",
        ["该项目暂无环境，请先在项目设置中添加环境"] = "이 프로젝트에는 아직 환경이 없습니다",
        ["搜索配置键"] = "구성 키 검색",
        ["新建配置项"] = "구성 추가",
        ["还没有配置项"] = "아직 구성 항목이 없습니다",
        ["新建后会显示在这里"] = "새 구성 항목이 여기에 표시됩니다",
        ["创建后可在这里维护各环境的配置值"] = "생성 후 여기에서 환경별 값을 관리할 수 있습니다",
        ["值"] = "값",
        ["更新于"] = "업데이트",
        ["操作"] = "작업",
        ["选择配置项"] = "구성 항목 선택",
        ["各环境取值"] = "환경별 값",
        ["项目管理"] = "프로젝트 관리",
        ["个项目 · 管理所有项目及其环境"] = "개 프로젝트 · 모든 프로젝트와 환경 관리",
        ["新建项目"] = "프로젝트 추가",
        ["搜索项目名称或标识"] = "프로젝트 이름 또는 키 검색",
        ["个环境"] = "개 환경",
        ["项配置"] = "개 구성",
        ["创建于"] = "생성일",
        ["管理配置"] = "구성 관리",
        ["编辑项目"] = "프로젝트 편집",
        ["编辑配置项"] = "구성 편집",
        ["名称"] = "이름",
        ["标识"] = "키",
        ["项目唯一标识，用于 API 调用"] = "API 호출에 사용하는 프로젝트 고유 키",
        ["描述"] = "설명",
        ["选填"] = "선택",
        ["环境"] = "환경",
        ["多个环境用逗号分隔"] = "여러 환경은 쉼표로 구분",
        ["取消"] = "취소",
        ["保存"] = "저장",
        ["配置键，项目内唯一"] = "프로젝트 내에서 고유한 구성 키",
        ["敏感配置"] = "민감 구성",
        ["环境取值"] = "환경 값",
        ["删除"] = "삭제",
        ["关闭"] = "닫기",
        ["删除确认"] = "삭제 확인",
        ["请输入名称"] = "이름을 입력하세요",
        ["请输入配置键"] = "구성 키를 입력하세요",
        ["确定删除该项目吗？其下所有配置将一并删除，此操作不可恢复。"] = "이 프로젝트를 삭제할까요? 하위 구성도 함께 삭제되며 되돌릴 수 없습니다.",
        ["确定删除该配置项吗？它在所有环境下的值都将被删除。"] = "이 구성 항목을 삭제할까요? 모든 환경의 값이 삭제됩니다."
    };

    internal static readonly IReadOnlyDictionary<string, string> Spanish = new Dictionary<string, string> {
        ["配置管理"] = "Configuración",
        ["选择项目"] = "Seleccionar proyecto",
        ["搜索项目"] = "Buscar proyectos",
        ["暂无数据"] = "Sin datos",
        ["请先在“项目管理”中创建一个项目"] = "Crea primero un proyecto en Proyectos",
        ["按环境"] = "Por entorno",
        ["按配置"] = "Por configuración",
        ["选择一个环境，管理该环境下的全部配置"] = "Selecciona un entorno y gestiona sus configuraciones",
        ["选择一个配置项，管理它在所有环境下的值"] = "Selecciona una configuración y gestiona sus valores",
        ["该项目暂无环境，请先在项目设置中添加环境"] = "Este proyecto no tiene entornos",
        ["搜索配置键"] = "Buscar claves",
        ["新建配置项"] = "Nueva configuración",
        ["还没有配置项"] = "No hay configuraciones",
        ["新建后会显示在这里"] = "Las nuevas configuraciones aparecerán aquí",
        ["创建后可在这里维护各环境的配置值"] = "Crea una para gestionar valores por entorno",
        ["值"] = "Valor",
        ["更新于"] = "Actualizado",
        ["操作"] = "Acciones",
        ["选择配置项"] = "Seleccionar configuración",
        ["各环境取值"] = "Valores por entorno",
        ["项目管理"] = "Proyectos",
        ["个项目 · 管理所有项目及其环境"] = "proyectos · Gestiona proyectos y entornos",
        ["新建项目"] = "Nuevo proyecto",
        ["搜索项目名称或标识"] = "Buscar por nombre o clave",
        ["个环境"] = "entornos",
        ["项配置"] = "configuraciones",
        ["创建于"] = "Creado",
        ["管理配置"] = "Gestionar configuración",
        ["编辑项目"] = "Editar proyecto",
        ["编辑配置项"] = "Editar configuración",
        ["名称"] = "Nombre",
        ["标识"] = "Clave",
        ["项目唯一标识，用于 API 调用"] = "Clave única del proyecto para API",
        ["描述"] = "Descripción",
        ["选填"] = "Opcional",
        ["环境"] = "Entornos",
        ["多个环境用逗号分隔"] = "Separa entornos con comas",
        ["取消"] = "Cancelar",
        ["保存"] = "Guardar",
        ["配置键，项目内唯一"] = "Clave única dentro del proyecto",
        ["敏感配置"] = "Configuración sensible",
        ["环境取值"] = "Valores de entorno",
        ["删除"] = "Eliminar",
        ["关闭"] = "Cerrar",
        ["删除确认"] = "Confirmar eliminación",
        ["请输入名称"] = "Introduce un nombre",
        ["请输入配置键"] = "Introduce una clave de configuración",
        ["确定删除该项目吗？其下所有配置将一并删除，此操作不可恢复。"] = "¿Eliminar este proyecto? También se eliminarán sus configuraciones. No se puede deshacer.",
        ["确定删除该配置项吗？它在所有环境下的值都将被删除。"] = "¿Eliminar esta configuración? Se eliminarán sus valores en todos los entornos."
    };
}